name: Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: yoriiis/actions/.github/workflows/coverage.yml@main
