name: QA

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# test
jobs:
  test:
    uses: yoriiis/actions/.github/workflows/qa.yml@main
